import {resolvePosition,validateProject,clamp} from './app/project.js?v=20261005a';
import {ModelViewer,parts} from './app/viewer.js?v=20261005a';
import {createPlayback} from './playback.js?v=20260928c';
const $=id=>document.getElementById(id);
let project,manifest,position=0,current,renderedChapter=null,ready=false,serial=0,loadingItems=[],error=null,selected=null,context=false,view='iso',preset='assembled';
const checks={},hidden=new Set(),diagnostics=$('viewer-diagnostics');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let viewer;
const playback=createPlayback({getTotal:()=>project?.totalSteps||0,getStep:()=>position,onStep:value=>setPosition(value),onState:playing=>{$('play').textContent=playing?'Ⅱ Pause':'▶ Play';$('play').setAttribute('aria-label',playing?'Pause project':'Play project');$('play').setAttribute('aria-pressed',String(playing))}});
function publish(){if(!project)return;const state=getState();diagnostics.textContent=JSON.stringify(state);window.dispatchEvent(new CustomEvent('wbp:statechange',{detail:state}));}
function getState(){return {schemaVersion:1,projectId:project?.id,ready,playing:playback.isPlaying(),position,totalSteps:project?.totalSteps,chapterId:current?.chapter.id,chapterProgress:current?.progress,context,preset,selected,views:viewer?.state()||[],loadedPhases:[...(viewer?.cache.keys()||[])],contextLoaded:viewer?.context.size||0,contextTotal:contextLayers().length,loadingPercent:$('load-progress').hasAttribute('value')?Number($('load-progress').value):null,error};}
function contextLayers(){return manifest?.layers.filter(l=>!['target_building','building_details','source_reference'].includes(l.group))||[];}
function loadingProgress(event){if(event?.fatal){showError(event.fatal);return;}if($('loading').hidden||error)return;let total=0,done=0,preparing=false;for(const item of loadingItems){const value=viewer?.progress.get(item.key);total+=item.bytes;done+=item.bytes*(value?.fraction||0);preparing||=value?.state==='prepare';}
 if(total){const percent=Math.min(100,Math.max(0,Math.floor(done/total*100)));$('load-progress').value=percent;$('load-percent').textContent=percent+'%';$('loading-detail').textContent=preparing?'Preparing geometry and materials…':context?'Loading models and airport context…':'Downloading the model geometry and materials…';}else{$('load-progress').removeAttribute('value');$('load-percent').textContent='—';}publish();}
function showLoading(phases,title){ready=false;error=null;loadingItems=phases.map(p=>({key:p.id,bytes:p.bytes}));if(context)loadingItems.push(...contextLayers().map(l=>({key:'context:'+l.id,bytes:l.bytes||1})));$('loading-title').textContent=title;$('loading').hidden=false;$('retry').hidden=true;$('skip-context').hidden=!context;$('stage').setAttribute('aria-busy','true');$('play').disabled=true;loadingProgress();}
function showError(message){playback.pause();ready=false;error=message;$('loading').hidden=false;$('loading-title').textContent='Let’s try that again.';$('loading-detail').textContent=message;$('retry').hidden=false;$('skip-context').hidden=!context;$('stage').setAttribute('aria-busy','false');$('play').disabled=true;publish();}
function finishLoading(){ready=true;error=null;$('loading').hidden=true;$('stage').setAttribute('aria-busy','false');$('play').disabled=false;publish();}
function updateUI(){
 const c=current.chapter,compare=current.views.length===2;document.body.classList.toggle('comparing',compare);$('pane-1').hidden=!compare;$('option-0').hidden=!compare;$('comparison-note').hidden=!compare;$('chapter-label').textContent='CHAPTER '+String(project.chapters.indexOf(c)+1).padStart(2,'0')+' / 04';$('chapter-subtitle').textContent=c.subtitle;
 for(let i=0;i<current.views.length;i++){const v=current.views[i];$('count-'+i).textContent=`STEP ${v.step} / ${v.phase.stages.length}`;$('title-'+i).textContent=v.caption.title;$('description-'+i).textContent=v.caption.description;}
 document.querySelectorAll('[data-chapter]').forEach(b=>{if(b.dataset.chapter===c.id)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});$('progress').value=position;const percent=Math.round(position/project.totalSteps*100);$('overall-progress').textContent=percent+'%';$('progress').style.setProperty('--progress',percent+'%');$('progress').setAttribute('aria-valuetext',`${percent}% · ${c.title} · ${Math.round(current.progress*100)}% of chapter`);$('timeline-label').textContent=c.title+' · '+Math.round(current.progress*100)+'%';$('previous-step').disabled=position===0;$('next-step').disabled=position===project.totalSteps;
 document.body.classList.toggle('airport-context',context);$('context-toggle').setAttribute('aria-pressed',String(context));document.querySelector('[data-preset=substructure]').hidden=!['removal','foundations'].includes(c.id);
}
function applyOptions(){viewer.options={context,t1:$('t1').checked,surroundings:$('surroundings').checked,hidden};viewer.apply();publish();}
function display(){if(renderedChapter!==current.chapter.id){viewer.setModels(current.views);renderedChapter=current.chapter.id;}else viewer.setSteps(current.views);applyOptions();viewer.render();finishLoading();}
async function setPosition(value){
 if(!project)return;viewer.contextWanted=context;position=resolvePosition(project,value).value;current=resolvePosition(project,position);const token=++serial;updateUI();const phases=current.views.map(v=>v.phase),hasContext=!context||contextLayers().every(l=>viewer.context.has(l.id));
 if(phases.every(p=>viewer.cache.has(p.id))&&hasContext){display();return;}
 playback.pause();showLoading(phases,current.views.length===2?'Preparing both options.':'Loading '+current.chapter.title+'.');
 try{await Promise.all([...phases.map(p=>viewer.load(p)),...(context?[viewer.loadContext(contextLayers())]:[])]);if(token!==serial)return;display();}catch(e){if(token!==serial)return;showError(e.name==='AbortError'?'The connection timed out. Your progress is saved; try again.':'We couldn’t load this view. Check your connection and try again.');console.error(e);}
}
function choosePreset(value){preset=value;hidden.clear();if(value==='roof'||value==='inside')hidden.add('roof');if(value==='inside')for(const p of ['facade','canopy','ground'])hidden.add(p);if(value==='substructure')for(const p of ['roof','facade','structure','ground','interior','canopy','loading','temporary'])hidden.add(p);for(const [key,input]of Object.entries(checks))input.checked=!hidden.has(key);document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===value)));applyOptions();}
async function togglePlay(){if(playback.isPlaying()){playback.pause();publish();return;}if(!ready)return;const token=++serial;showLoading(project.phases,'Preparing the complete journey.');try{await Promise.all(project.phases.map(p=>viewer.load(p)));if(token!==serial)return;finishLoading();playback.play();publish();}catch(e){if(token===serial)showError('The complete journey couldn’t load. Try again or choose a chapter.');console.error(e);}}
function pick(data){selected={phaseId:data.phaseId,componentId:data.group?data.phaseId+':'+data.group:null,category:data.category,localPoint:data.point};const [x,y,z]=data.point,o=project.origin;$('position').textContent=`${parts[data.category]||'Airport context'} · HK1980 E ${(x+o.easting).toFixed(2)} / N ${(o.northing-z).toFixed(2)} / H ${(y+o.height).toFixed(2)} m`;publish();}
try{
 viewer=new ModelViewer({host:$('panes'),surfaces:[$('surface-0'),$('surface-1')],onProgress:loadingProgress,onPick:pick});
 viewer.renderer.setAnimationLoop(time=>{playback.tick(time);viewer.render();});
 for(const [id,label]of Object.entries(parts)){if(['t1_context','site_extras'].includes(id))continue;const row=document.createElement('label');row.className='check-row';const input=document.createElement('input');input.type='checkbox';input.checked=true;input.setAttribute('aria-label',label);row.append(input,document.createTextNode(label));$('parts').append(row);checks[id]=input;input.onchange=()=>{preset='custom';input.checked?hidden.delete(id):hidden.add(id);document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed','false'));applyOptions();};}
 $('play').onclick=togglePlay;$('progress').oninput=e=>{playback.pause();setPosition(e.target.value)};$('previous-step').onclick=()=>{playback.pause();setPosition(position-1)};$('next-step').onclick=()=>{playback.pause();setPosition(position+1)};$('restore').onclick=()=>{playback.pause();choosePreset('assembled');setPosition(0)};
 $('context-toggle').onclick=()=>{playback.pause();context=!context;setPosition(position)};$('skip-context').onclick=()=>{context=false;setPosition(position)};$('retry').onclick=()=>project?setPosition(position):location.reload();
 $('t1').onchange=applyOptions;$('surroundings').onchange=applyOptions;document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>choosePreset(b.dataset.preset));
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;viewer.fit(view);document.querySelectorAll('[data-view]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.view===view)));publish()});$('fit').onclick=()=>{viewer.fit(view);publish()};$('rotate').onclick=()=>{viewer.autoRotate=!viewer.autoRotate;$('rotate').setAttribute('aria-pressed',String(viewer.autoRotate))};
 $('panel-toggle').onclick=()=>{playback.pause();$('settings-panel').showModal();$('panel-toggle').setAttribute('aria-expanded','true')};$('close-settings').onclick=()=>$('settings-panel').close();$('settings-panel').addEventListener('close',()=>{$('panel-toggle').setAttribute('aria-expanded','false');$('panel-toggle').focus()});$('settings-panel').addEventListener('click',e=>{if(e.target===$('settings-panel')){const b=e.target.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)e.target.close();}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)playback.pause()});document.addEventListener('keydown',()=>document.body.classList.add('keyboard-input'));document.addEventListener('pointerdown',()=>document.body.classList.remove('keyboard-input'));reduced.addEventListener('change',()=>{if(reduced.matches){viewer.autoRotate=false;$('rotate').setAttribute('aria-pressed','false')}});
 const responses=await Promise.all([fetch('./data/project.json?v=20261005a'),fetch('./manifest.json?v=20260928c')]);if(responses.some(r=>!r.ok))throw Error('Project data unavailable');[project,manifest]=await Promise.all(responses.map(r=>r.json()));validateProject(project);$('progress').max=project.totalSteps;
 for(const [i,c]of project.chapters.entries()){const b=document.createElement('button');b.className='chapter-button';b.dataset.chapter=c.id;const number=document.createElement('span');number.className='chapter-number';number.textContent=String(i+1).padStart(2,'0');b.append(number,document.createTextNode(c.shortTitle));b.setAttribute('aria-label','Chapter '+(i+1)+': '+c.title);b.onclick=()=>{playback.pause();setPosition(c.start)};$('chapters').append(b);if(i){const mark=document.createElement('span');mark.style.left=c.start/project.totalSteps*100+'%';$('timeline-markers').append(mark);}}
 await setPosition(0);
 // A small, validated integration surface for future tools. No AI service is connected.
 window.wbpViewer=Object.freeze({getState, getProject:()=>structuredClone(project),setProgress:value=>{playback.pause();return setPosition(clamp(value,0,1)*project.totalSteps)},jumpToChapter:id=>{const c=project.chapters.find(c=>c.id===id);if(!c)throw Error('Unknown chapter');playback.pause();return setPosition(c.start)},setContext:enabled=>{context=Boolean(enabled);return setPosition(position)}});
 setInterval(publish,1000);
}catch(e){showError('The viewer couldn’t start. Check your connection and graphics support, then try again.');console.error(e);}
