import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {KTX2Loader} from 'three/addons/loaders/KTX2Loader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {downloadFraction,visibility} from './project.js';

export const parts={foundation:'Piles, caps & foundation beams',bridge:'Footbridge',temporary:'Hoarding & temporary works',ground:'Ground & excavation',roof:'Roof & skylights',facade:'Walls & windows',structure:'Structure & slabs',interior:'Interior platforms & equipment',canopy:'Entrance & rear canopies',loading:'Loading platforms & safety equipment',t1_context:'T1 canopy',site_extras:'Other site components'};
export class ModelViewer {
 constructor({host,surfaces,onProgress,onPick,onInteract}){
  this.host=host;this.onProgress=onProgress;this.onPick=onPick;this.cache=new Map();this.loads=new Map();this.progress=new Map();this.context=new Map();this.contextLoads=new Map();this.views=[];this.active=0;this.comparing=false;this.autoRotate=false;this.view='iso';this.options={context:false,t1:true,surroundings:true,hidden:new Set()};
  this.renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,logarithmicDepthBuffer:true});this.renderer.domElement.id='render-canvas';host.prepend(this.renderer.domElement);this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.setClearColor(0,0);this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.renderer.outputColorSpace=THREE.SRGBColorSpace;
  this.loader=new GLTFLoader().setDRACOLoader(new DRACOLoader().setDecoderPath('./vendor/three/examples/jsm/libs/draco/gltf/')).setKTX2Loader(new KTX2Loader().setTranscoderPath('./vendor/three/examples/jsm/libs/basis/').detectSupport(this.renderer)).setMeshoptDecoder(MeshoptDecoder);
  const pmrem=new THREE.PMREMGenerator(this.renderer),room=new RoomEnvironment();this.env=pmrem.fromScene(room,.025);room.dispose();pmrem.dispose();
  for(const [index,surface] of surfaces.entries()){
   const scene=new THREE.Scene();scene.environment=this.env.texture;scene.environmentIntensity=.5;scene.add(new THREE.HemisphereLight(0xffffff,0x8e9980,1.2));const sun=new THREE.DirectionalLight(0xfff5df,2.1);sun.position.set(-150,250,150);scene.add(sun);
   const camera=new THREE.OrthographicCamera(-90,90,75,-75,.1,20000),controls=new OrbitControls(camera,surface);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.495;controls.autoRotateSpeed=.6;controls.addEventListener('start',()=>{this.active=index;onInteract?.()});
   const grid=new THREE.GridHelper(150,30,0x9cabca,0xb7c4d8);grid.material.transparent=true;grid.material.opacity=.1;scene.add(grid);
   const v={scene,camera,controls,surface,grid,phase:null,root:null,contextRoot:new THREE.Group(),groups:[],step:0};scene.add(v.contextRoot);this.views.push(v);
   let down;surface.addEventListener('pointerdown',e=>{this.active=index;down=[e.clientX,e.clientY]});surface.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<5)this.pick(index,e)});
   surface.addEventListener('keydown',e=>{if(e.key==='Home'){e.preventDefault();onInteract?.();this.fit()}});
  }
  this.observer=new ResizeObserver(()=>{this.resize();this.fit()});this.observer.observe(host);for(const surface of surfaces)this.observer.observe(surface);
  this.renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();this.onProgress({fatal:'The graphics connection was interrupted. Reload the page to continue.'})});
 }
 prepare(root){root.traverse(o=>{if(!o.isMesh)return;for(const m of Array.isArray(o.material)?o.material:[o.material])for(const key of ['map','normalMap'])if(m[key])m[key].anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());});}
 async download(url,bytes,key){
  const controller=new AbortController();let timer;const arm=()=>{clearTimeout(timer);timer=setTimeout(()=>controller.abort(),60000)};arm();
  try{const response=await fetch(url,{signal:controller.signal});if(!response.ok)throw Error('Download failed ('+response.status+')');const reader=response.body?.getReader();if(!reader)return await response.arrayBuffer();let received=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.byteLength;arm();this.progress.set(key,{fraction:(downloadFraction(received,bytes)??0)*.9,state:'download'});this.onProgress();}const data=new Uint8Array(received);let offset=0;for(const c of chunks){data.set(c,offset);offset+=c.length;}return data.buffer;}finally{clearTimeout(timer)}
 }
 async load(phase){
  if(this.cache.has(phase.id))return this.cache.get(phase.id);if(this.loads.has(phase.id))return this.loads.get(phase.id);
  const key=phase.id;this.progress.set(key,{fraction:0,state:'download'});
  const task=(async()=>{try{const data=await this.download(phase.asset+'?v='+phase.assetVersion,phase.bytes,key);this.progress.set(key,{fraction:.9,state:'prepare'});this.onProgress();await new Promise(resolve=>requestAnimationFrame(resolve));const gltf=await this.loader.parseAsync(data,new URL('.',location.href).href);this.prepare(gltf.scene);gltf.scene.updateMatrixWorld(true);const bounds=new THREE.Box3();gltf.scene.traverse(o=>{if(!o.isMesh)return;const box=new THREE.Box3().setFromObject(o);if(Math.max(...box.min.toArray().map(Math.abs),...box.max.toArray().map(Math.abs))<250)bounds.union(box)});if(bounds.isEmpty())throw Error('No local model geometry');const projected={};
  for(const [view,dir]of Object.entries({iso:[150,140,95],plan:[0,200,.01],front:[-160,30,50]})){
   const c=new THREE.OrthographicCamera();c.position.set(...dir);c.lookAt(0,0,0);c.updateMatrixWorld(true);const box=new THREE.Box3(),point=new THREE.Vector3();
   gltf.scene.traverse(o=>{if(!o.isMesh||o.userData.wbpPart==='site_extras')return;const attr=o.geometry.getAttribute('position');for(let i=0;i<attr.count;i++){point.fromBufferAttribute(attr,i).applyMatrix4(o.matrixWorld);if(Math.max(Math.abs(point.x),Math.abs(point.y),Math.abs(point.z))<250)box.expandByPoint(point.applyMatrix4(c.matrixWorldInverse));}});projected[view]=box;
  }
  const framingPoints=[],groupBoxes=new Map();
  gltf.scene.traverse(o=>{if(!o.isMesh)return;let group=o;while(group&&!group.userData.sequenceGroup)group=group.parent;if(group?.userData.wbpPart==='site_extras')return;const box=new THREE.Box3().setFromObject(o);if(box.isEmpty()||Math.max(...box.min.toArray().map(Math.abs),...box.max.toArray().map(Math.abs))>=250)return;for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z])framingPoints.push(new THREE.Vector3(x,y,z));if(group){const id=group.userData.sequenceGroup;if(!groupBoxes.has(id))groupBoxes.set(id,new THREE.Box3());groupBoxes.get(id).union(box);}});
  const entry={root:gltf.scene,bounds,projected,framingPoints,groupBoxes};this.cache.set(key,entry);this.progress.set(key,{fraction:1,state:'ready'});this.onProgress();return entry;}catch(e){this.progress.set(key,{fraction:0,state:'error'});throw e}finally{this.loads.delete(key)}})();this.loads.set(key,task);return task;
 }
 async cutout(root,layer){
  if(layer.id==='airport_entrance')return;
  if(!this.footprintPromise)this.footprintPromise=fetch('./models/context-footprint.bin?v=20260928c').then(async r=>{if(!r.ok)throw Error('Ground cutout unavailable');const t=new THREE.DataTexture(new Uint8Array(await r.arrayBuffer()),512,512,THREE.RedFormat);t.needsUpdate=true;return t}).catch(e=>{this.footprintPromise=null;throw e});
  const footprint=await this.footprintPromise;
  root.traverse(mesh=>{if(!mesh.isMesh)return;const adapt=original=>{const mat=original.clone();mat.onBeforeCompile=shader=>{shader.uniforms.siteFootprint={value:footprint};shader.vertexShader='varying vec3 siteWorld;\n'+shader.vertexShader.replace('#include <project_vertex>','#include <project_vertex>\nsiteWorld = (modelMatrix * vec4(transformed, 1.0)).xyz;');shader.fragmentShader='uniform sampler2D siteFootprint;\nvarying vec3 siteWorld;\n'+shader.fragmentShader.replace('#include <clipping_planes_fragment>',`#include <clipping_planes_fragment>
vec2 localSite=vec2(.3241441548*siteWorld.x+.946007669*siteWorld.z-45.40784073,.946007669*siteWorld.x-.3241441548*siteWorld.z+34.13520813);
vec2 uv=(localSite-vec2(-58.,-14.))/vec2(103.,40.);
if(siteWorld.y<8.0 && all(greaterThanEqual(uv,vec2(0.))) && all(lessThanEqual(uv,vec2(1.))) && texture2D(siteFootprint,uv).r>.5)discard;`)};mat.customProgramCacheKey=()=> 'source-soil-footprint';return mat};mesh.material=Array.isArray(mesh.material)?mesh.material.map(adapt):adapt(mesh.material)});
 }
 async loadContext(layers){
  // Two concurrent requests keep the connection responsive without flooding mobile devices.
  let cursor=0;const worker=async()=>{while(cursor<layers.length){if(!this.contextWanted)return;const layer=layers[cursor++];if(this.context.has(layer.id))continue;let task=this.contextLoads.get(layer.id);if(!task){task=(async()=>{const key='context:'+layer.id;try{const data=await this.download(layer.url,layer.bytes,key);this.progress.set(key,{fraction:.9,state:'prepare'});this.onProgress();const gltf=await this.loader.parseAsync(data,new URL('.',location.href).href);this.prepare(gltf.scene);await this.cutout(gltf.scene,layer);this.context.set(layer.id,{root:gltf.scene,group:layer.group});this.progress.set(key,{fraction:1,state:'ready'});this.onProgress();}finally{this.contextLoads.delete(layer.id)}})();this.contextLoads.set(layer.id,task);}await task;}};await Promise.all([worker(),worker()]);
 }
 setModels(views){
  this.comparing=views.length===2;this.active=0;this.bounds=new THREE.Box3();
  this.views.forEach((v,i)=>{const model=views[i];if(!model){if(v.root)v.scene.remove(v.root);v.root=null;v.phase=null;return;}const cached=this.cache.get(model.phase.id);this.bounds.union(cached.bounds);if(v.phase?.id!==model.phase.id){if(v.root)v.scene.remove(v.root);v.root=cached.root.clone(true);v.scene.add(v.root);v.phase=model.phase;v.groups=[];v.root.traverse(o=>{if(o.userData.sequenceGroup)v.groups.push(o)});}v.step=model.step;});
  this.center=this.bounds.getCenter(new THREE.Vector3());for(const v of this.views)v.grid.position.set(this.center.x,Math.min(5.1,this.center.y-2),this.center.z);this.apply();this.resize();this.fit();
 }
 setSteps(views){for(let i=0;i<views.length;i++)this.views[i].step=views[i].step;this.apply();}
 apply(){for(const v of this.views){if(!v.phase)continue;const states=visibility(v.phase,v.step);for(const node of v.groups){const part=node.userData.wbpPart;node.visible=states[node.userData.sequenceGroup]!==false&&(part==='t1_context'?this.options.t1:part==='site_extras'?this.options.context:!this.options.hidden.has(part));}v.grid.visible=!this.options.context;for(const [id,data]of this.context){let root=v.contextRoot.children.find(o=>o.name===id);if(!root){root=data.root.clone(true);root.name=id;root.userData.contextGroup=data.group;v.contextRoot.add(root)}root.visible=this.options.context&&(data.group!=='surrounding_buildings'||this.options.surroundings);}}}
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(w&&h)this.renderer.setSize(w,h);for(const v of this.views){const frame=matchMedia('(min-width:761px)').matches?v.surface.parentElement:v.surface;const w=frame.clientWidth,h=frame.clientHeight;if(!w||!h)continue;v.camera.left=-135*w/h/2;v.camera.right=135*w/h/2;v.camera.top=67.5;v.camera.bottom=-67.5;v.camera.updateProjectionMatrix();}}
 fit(view=this.view){if(this.guided)return;this.view=view;if(!this.center||!this.bounds)return;const dirs={iso:[150,140,95],plan:[0,200,.01],front:[-160,30,50]};for(const v of this.views){if(!v.phase)continue;const c=v.camera;c.position.copy(this.center).add(new THREE.Vector3(...dirs[view]));c.lookAt(this.center);c.updateMatrixWorld(true);const projected=new THREE.Box3();for(const active of this.views)if(active.phase)projected.union(this.cache.get(active.phase.id).projected[view]);const pc=projected.getCenter(new THREE.Vector3()),right=new THREE.Vector3().setFromMatrixColumn(c.matrixWorld,0),up=new THREE.Vector3().setFromMatrixColumn(c.matrixWorld,1),target=this.center.clone().addScaledVector(right,pc.x-this.center.dot(right)).addScaledVector(up,pc.y-this.center.dot(up));c.position.copy(target).add(new THREE.Vector3(...dirs[view]));c.lookAt(target);const size=projected.getSize(new THREE.Vector3()),frame=matchMedia('(min-width:761px)').matches?v.surface.parentElement:v.surface,fit=Math.min((c.right-c.left)*v.surface.clientWidth/frame.clientWidth/Math.max(1,size.x),135*v.surface.clientHeight/frame.clientHeight/Math.max(1,size.y))*.88;c.zoom=fit;c.updateProjectionMatrix();v.fitZoom=fit;v.controls.target.copy(target);v.controls.cursor.copy(target);v.controls.maxTargetRadius=this.bounds.getSize(new THREE.Vector3()).length()*.6;v.controls.minZoom=fit*.6;v.controls.maxZoom=fit*12;v.controls.update();}}
 render(){const r=this.renderer,area=this.host.getBoundingClientRect(),master=this.views[this.active];if(!master.phase)return;master.controls.autoRotate=this.autoRotate;if(!this.guided)master.controls.update();if(this.comparing&&!this.guided){const other=this.views[1-this.active];other.camera.position.copy(master.camera.position);other.camera.quaternion.copy(master.camera.quaternion);other.camera.zoom=master.camera.zoom/master.fitZoom*other.fitZoom;other.camera.updateProjectionMatrix();other.controls.target.copy(master.controls.target);}
  r.setScissorTest(false);r.setViewport(0,0,area.width,area.height);r.clear();r.setScissorTest(true);for(const v of this.views){if(!v.phase)continue;const frame=matchMedia('(min-width:761px)').matches?v.surface.parentElement:v.surface;const rect=frame.getBoundingClientRect();if(!rect.width||!rect.height)continue;const left=rect.left-area.left,bottom=area.bottom-rect.bottom;r.setViewport(left,bottom,rect.width,rect.height);r.setScissor(left,bottom,rect.width,rect.height);r.render(v.scene,v.camera);}r.setScissorTest(false);
 }
 pick(i,e){const v=this.views[i];if(!v.root)return;const frame=matchMedia('(min-width:761px)').matches?v.surface.parentElement:v.surface,rect=frame.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2),v.camera);const visible=o=>{for(let p=o;p;p=p.parent)if(!p.visible)return false;return true};const hit=ray.intersectObjects([v.root,v.contextRoot],true).find(h=>visible(h.object));if(!hit)return;let n=hit.object;while(n&&!n.userData.sequenceGroup)n=n.parent;this.onPick({phaseId:v.phase.id,group:n?.userData.sequenceGroup,category:n?.userData.wbpPart,point:hit.point.toArray()});}
 state(){return this.views.filter(v=>v.phase).map(v=>({phase:v.phase.id,step:v.step,visibleGroups:[...new Set(v.groups.filter(o=>o.visible).map(o=>o.userData.sequenceGroup))],zoom:v.camera.zoom,camera:v.camera.position.toArray(),target:v.controls.target.toArray()}));}
}
